name: Unit Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'lib/**'
      - '.github/workflows/test.yml'

jobs:
  build_wasm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build and push
      working-directory: ./lib/
      run: docker run -v `pwd`:/src ubuntu:focal-20220113 /bin/bash /src/build-lib.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wasm
        path: ./lib/wasi-lab/qjs-wasi/build/qjs.wasm

  run_unittests:
    needs: build_wasm
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet: [6.0.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Prepare artifact directory
        shell: bash
        working-directory: ./lib/
        run: mkdir ./lib/wasi-lab/qjs-wasi/build

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: wasm
          path: ./lib/wasi-lab/qjs-wasi/build/qjs.wasm

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build projects
        working-directory: ./src/
        run: dotnet build

      - name: Run unit tests
        working-directory: ./src/
        run: dotnet test
